[[tau-installation]]
= Installation

TAU (Tuning and Analysis Utilities) is a portable profiling and tracing toolkit for performance analysis of parallel programs written in Fortran, C++, C, Java and Python. The model that TAU uses to profile parallel, multi-threaded programs maintains performance data for each thread, context, and node in use by an application. The profiling instrumentation needed to implement the model captures data for functions, methods, basic blocks, and statement execution at these levels. All C++ language features are supported in the TAU profiling instrumentation including templates and namespaces, which is available through an API at the library or application level. The API also provides selection of profiling groups for organizing and controlling instrumentation. The instrumentation can be inserted in the source code using an automatic instrumentor tool based on the Program Database Toolkit (PDT), dynamically using DyninstAPI, at runtime in the Java virtual machine, or manually using the instrumentation API. TAU's profile visualization tool, paraprof, provides graphical displays of all the performance analysis results, in aggregate and single node/context/thread forms. The user can quickly identify sources of performance bottlenecks in the application using the graphical interface. In addition, TAU can generate event traces that can be displayed with the Vampir or Paraver trace visualization tools. This chapter discusses installation of the TAU portable profiling package.

Some tau options allow external resources to be automatically downloaded and built when TAU is configured. To obtain these resources in a single package download http://tau.uoregon.edu/ext.tgz and unpack it in TAU's root directory. When you configure TAU with: * -bfd=download * -unwind=download * -ompt=download these packages will be provided by the ext.tgz package and no additional network activity will be required.

[[installing-tau]]
== Installing TAU
=== Know what options you will need
Each TAU configuration results in a single `Makefile`. These `Makefiles` denote the configuration that produced it and is used by the user to select the TAU libraries/scripts associated with its configuration. (These makefiles are named after the configuration options, ie. TAU configured with MPI, PDT, PGI compilers and the '-nocomm' option is named: `Makefile.tau-nocomm-mpi-pdt-pgi`). On most machines several configuration of TAU will need to be built in order to take full advantage of the many features of TAU. This section should help you decide on the smallest set of configuration you will need to build.

The options used to configure TAU can be grouped into two categories: * External packages: TAU will use these when instrumenting or measuring an application. Configuring with these options does not force the user to use these packages, ie: configuring with PDT does not force the user to use source code based instrumentation (they can use compiler based instrumentation instead). Similarly configuring with PAPI does not forces the user to select any PAPI counters when profiling. The only exception is configuring with the epilog (scalasca) tracing package. This will replace the TAU tracer with the epliog one, a single configuration cannot use both tracers. * Compiler and MPI options: these control the behavior of TAU when it compiles the instrumented application. TAU provides compiler wrapper scripts, these options control which compiler TAU will wrap, These options are determinative: select only options that are compatible. For example, when configuring with MPI use a version of MPI compatible with the compiler you select.

The `configure` shell script attempts to guess correct values for various system-dependent variables used during compilation (compilers and system architecture), other options need to be specified on the command line.

The following are the most important command-line options are available to configure:

=== Common configuration options
==== Select compiler
TAU defaults to using any compilers found in the environment. To use a specific compiler use these options:

* -c++=<C++ compiler>
* -cc=<C Compiler>
* -fortran=<Fortran Compiler>


==== Using MPI
To profile a program that use MPI configure TAU with these options:

* -mpi
* -mpiinc=<directory>
* -mpilib=<directory>
* -mpilibrary=<lib>
* -mpit


==== OpenMP
To profile programs using openmp use -openm and either OPARI option:

* -openmp
* -opari
* -opari1


=== Configuring with external packages
* -pdt=<directory>
* -pdt_c++=<C++ Compiler>
* -papi=<directory>
* -rocm
* -rocprofiler=<directory>
* -roctracer=<directory>
* -rocprofsdk
* -level_zero
* -epilog=<directory>
* -otf=<directory>
* -vtf=<directory>


=== More configuration options
* -PROFILEPHASE
* -prefix=<directory>
* -arch=<architecture>
* -tag=<Unique Name>
* -scalasca=<directory>
* -pthread
* -opari_region
* -opari_construct
* -pdtarch=<architecture>
* -papithreads
* -jdk=<directory>
* -apex
* -sos=<directory> or -sos=<download>
* -soscomm=<option>
* -beacon=<directory>
* -dyninst=<directory> or -dyninst=<download>
* -vampirtrace=<directory>
* -scorep=<directory> or -scorep=<download>
* -shmeminc=<directory>
* -shmemlib=<directory>
* -shmemlibrary=<lib>
* -ittnotify
* -nocomm
* -cuda=<directory>
* -gpi=<directory>
* -opencl=<directory>
* -armci=<directory>
* -epiloglib=<directory>
* -epilogbin=<directory>
* -epiloginc=<directory>
* -MPITRACE
* -python[3][=<directory>]
* -pythoninc=<directory>
* -pythonlib=<directory>
* -PROFILEMEMORY
* -PROFILECOMMUNICATORS
* -PROFILEHEADROOM
* -COMPENSATE
* -PROFILECOUNTERS
* -noex
* -useropt=<options-list>
* -mrnet=<mrnet source root>
* -mrnetlib=<mrnet libraries>
* -scorep=<scorep subsystem>
* -help


=== tau_setup
tau_setup is a GUI interface to the configure and installtau tools.

=== installtau script
To install multiple (typical) configurations of TAU at a site, you may use the script `installtau'. It takes options similar to those described above. It invokes ./configure <opts>; make clean install; to create multiple libraries that may be requested by the users at a site. The installtau script accepts the following options:

[source]
----
% installtau -help

TAU Configuration Utility
***************************************************
Usage: installtau [OPTIONS]
  where [OPTIONS] are:
-arch=<arch>
-fortran=<compiler>
-cc=<compiler>
-c++=<compiler>
-useropt=<options>
-pdt=<pdtdir>
-pdtcompdir=<compdir>
-pdt_c++=<C++ Compiler>
-papi=<papidir>
-vtf=<vtfdir>
-otf=<otfdir>
-dyninst=<dyninstdir>
-mpi
-mpiinc=<mpiincdir>
-mpilib=<mpilibdir>
-mpilibrary=<mpilibrary>
-perfinc=<directory>
-perflib=<directory>
-perflibrary=<library>
-mpi
-tag=<unique name>
-opari=<oparidir>
-epilog=<epilogdir>
-epiloginc=<absolute path to epilog include dir> (<epilog>/include default)
-epilogbin=<absolute path to epilog bin dir> (<epilog>/bin default)
-epiloglib=<absolute path to epilog lib dir> (<epilog>/lib default)
-prefix=<directory>
-exec-prefix=<directory>
-j=<num processes for parallel make>  (just -j for full parallel)

******************************************************************
----

These options are similar to the options used by the configure script.

=== upgradetau
This script is provided to rebuild all TAU configurations previously built in a different TAU source directory. Give this command the location of a previous version of tau followed by any additional configurations and it will rebuild tau with these same options.

=== tau_validate
This script will attempt to validate a tau installation. Its only argument is TAU's architecture directory. These are some options: * -v Verbose output * --html Output results in HTML * --build Only build * --run Only run

Here is a simple example: [source] ---- bash : ./tau_validate --html x86_64 &> results.html tcsh : ./tau_validate --html x86_64 >& results.html ----

[[platforms-supported]]
== Platforms Supported
TAU has been tested on the following platforms:

* LINUX Clusters
* Cray Compute Node Linux (XT5, XT6, XE6), X1, T3E, SV-1, XT3, and RedStorm
* IBM
* Sun Solaris
* Apple OS X
* SGI
* Accelerators
* Intel
* HP HP-UX
* HP Alpha Tru64
* NEC SX series vector machines
* On Hitachi machines, Hitachi KCC, g++ and Hitachi cc compilers
        may be used with TAU
* Fujitsu PRIMEPOWER
* Microsoft Window


NOTE: TAU has been tested with JDK 1.2, 1.3, 1.4.x under Solaris, SGI, IBM, Linux, and MacOS X.

[[software-requirements]]
== Software Requirements
* 1. Java v 1.5


